"""Emit main-text LaTeX tables for Study 2 from verified data + causal_stats.json.

Writes docs/paper/tables_causal.tex with:
  tab:factorial  -- harmful-revision counts X/180 per model x condition
  tab:contrasts  -- within-item paired contrasts (Delta, 95% CI, Holm p) + GEE OR
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "results"
stats = json.loads((RES / "reports" / "causal_stats.json").read_text())

# ordered by lab then capability for the table
RUN5 = [("GPT-3.5-turbo", "causal_powered_openai_gpt35turbo"),
        ("gpt-4o-mini", "causal_powered_openai_gpt4omini"),
        ("GPT-5-nano", "causal_powered_openai_gpt5nano"),
        ("GPT-5.4-mini", "causal_powered_openai_gpt54mini"),
        ("GPT-5.5", "causal_powered_openai_gpt55"),
        ("Claude Haiku 4.5", "causal_powered_bedrock_haiku45"),
        ("Claude Sonnet 4.6", "causal_powered_bedrock_sonnet46"),
        ("Claude Opus 4.6", "causal_powered_bedrock_opus46"),
        ("Llama-3.1-8B", "causal_powered_bedrock_llama31_8b"),
        ("Llama-3.3-70B", "causal_powered_bedrock_llama33_70b"),
        ("DeepSeek-V3.2", "causal_powered_bedrock_deepseek"),
        ("Mistral-Large-3", "causal_powered_bedrock_mistral"),
        ("Gemini-2.5-Flash", "causal_powered_openrouter_gemini25flash"),
        ("Qwen3-235B", "causal_powered_openrouter_qwen3_235b")]


def cells(run):
    s = json.loads((RES / run / "summary.json").read_text())
    return {k: v["x"] for k, v in s["headline"]["cells"].items()}


def stars(p):
    return "$^{***}$" if p < 1e-3 else "$^{**}$" if p < 1e-2 else "$^{*}$" if p < 0.05 else "\\,\\,\\,\\,\\,"


def pp(x):  # rate -> percentage points string
    return f"{x*100:+.1f}"


lines = ["% Auto-generated by scripts/make_causal_tables.py", ""]

# ---- Table: factorial counts
lines += [
    r"\begin{table}[t]\centering",
    r"\caption{Harmful-revision counts (of 180 items) in the powered factorial over "
    r"the unified 14-model panel. The five middle columns are withheld-source "
    r"conditions; `No pressure' is the withheld-source control with no contradictory "
    r"message. The last column is the strongest visible-source attack: it is $0/180$ "
    r"for every current model, and the only nonzero visible-source cell in the entire "
    r"design belongs to the legacy GPT-3.5-turbo.}",
    r"\label{tab:factorial}",
    r"\small",
    r"\begin{tabular}{lrrrrrr}",
    r"\toprule",
    r"Model & No pressure & Peer & Peer\,+\,cite & Expert & Expert\,+\,cite & Visible E+cite \\",
    r"\midrule",
]
order = ["hidden_no_pressure", "hidden_peer_none", "hidden_peer_fabricated",
         "hidden_expert_none", "hidden_expert_fabricated", "visible_expert_fabricated"]
for name, run in RUN5:
    c = cells(run)
    row = " & ".join(f"${c[k]}/180$" for k in order)
    lines.append(f"  {name} & {row} \\\\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

# ---- Table: contrasts
lines += [
    r"\begin{table}[t]\centering",
    r"\caption{Within-item paired contrasts under withheld source (same 180 items in "
    r"every cell). $\Delta$ is the harmful-revision rate difference in percentage points "
    r"with a 95\% bootstrap interval; significance is the exact McNemar test after "
    r"Holm correction across the full family of contrasts "
    r"($^{*}p{<}.05$, $^{**}p{<}.01$, $^{***}p{<}.001$). "
    r"`Peer$-$base' and `Expert$-$base' are excess over the no-pressure baseline; "
    r"`Expert$-$Peer' is the authority-vs-peer dissociation; "
    r"`$+$cite' is the change from adding a fabricated citation to the expert message.}",
    r"\label{tab:contrasts}",
    r"\scriptsize\setlength{\tabcolsep}{4pt}",
    r"\begin{tabular}{lccccc}",
    r"\toprule",
    r"Model & Baseline & Peer$-$base & Expert$-$base & Expert$-$Peer & Expert\,$+$cite \\",
    r" & (rate) & ($\Delta$pp) & ($\Delta$pp) & ($\Delta$pp) & ($\Delta$pp) \\",
    r"\midrule",
]
holm = stats["holm_adjusted_p"]
for name, run in RUN5:
    pc = stats["powered_contrasts"][name]
    base = stats["baseline_corrected"][name]["baseline_rate"]

    def cell(key):
        r = pc[key]
        hp = holm[f"{name}:{key}"]
        ci = r["diff_ci"]
        return f"{pp(r['diff'])}{stars(hp)} {{\\tiny[{ci[0]*100:+.0f},{ci[1]*100:+.0f}]}}"
    row = " & ".join([
        f"{base*100:.1f}\\%",
        cell("peer_vs_nopressure"),
        cell("expert_vs_nopressure"),
        cell("expert_vs_peer"),
        cell("cite_under_expert"),
    ])
    lines.append(f"  {name} & {row} \\\\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

(ROOT / "tables").mkdir(parents=True, exist_ok=True)
(ROOT / "tables" / "tables_causal.tex").write_text("\n".join(lines))
print("wrote tables/tables_causal.tex")
print("\n--- GEE expert ORs (susceptible models) ---")
for m in ("gpt-4o-mini", "Claude Haiku 4.5"):
    g = stats["gee"][m]
    print(f"  {m}: expert OR={g['expert']['or']:.1f} [{g['expert']['or_ci'][0]:.1f},{g['expert']['or_ci'][1]:.1f}]"
          f"  fab OR={g['fab']['or']:.2f} [{g['fab']['or_ci'][0]:.2f},{g['fab']['or_ci'][1]:.2f}]")
